### ISSUE TITLE
Missing translation examples for the /translations API endpoint

### ISSUE THREAD

**Issue by imankulov** [imankulov/linguee-api#10]
As outlined in https://github.com/imankulov/linguee-api/issues/7#issuecomment-826346069, in the second version of the API we lost the translation examples.

---

**[HTML page](https://www.linguee.pt/portugues-ingles/search?source=auto&query=obrigado)**

<img width="809" alt="Screenshot 2021-04-26 at 10 14 11" src="https://user-images.githubusercontent.com/75075/116058996-4e026c00-a678-11eb-8b4d-64091a7ce550.png">

---

**[API v1](https://linguee-api.herokuapp.com/api?q=obrigado&src=pt&dst=en)**

<img width="594" alt="Screenshot 2021-04-26 at 10 12 59" src="https://user-images.githubusercontent.com/75075/116059020-5490e380-a678-11eb-95e5-eb45e0953995.png">

---

**[API v2](https://linguee-api-v2.herokuapp.com/api/v2/translations?query=obrigado&src=pt&dst=en)**

<img width="483" alt="Screenshot 2021-04-26 at 10 13 58" src="https://user-images.githubusercontent.com/75075/116059008-5195f300-a678-11eb-8ada-31b72d4784e9.png">

**Comment by irico1997** [comment]
Sorry if this is not the right way to add, I don't typically comment on github. I don't think that this issue is fully fixed, with the translation request [for woman from en->de](https://linguee-api-v2.herokuapp.com/api/v2/translations?query=woman&src=en&dst=de&guess_direction=false) there are no examples, but [linguee has a few listed](https://www.linguee.com/english-german/search?source=auto&query=woman). I appreciate the work you did on this, it's pretty awesome for making anki decks with audio to make sure I get the pronunciation down. Really cool project!

**Comment by imankulov** [comment]
Hey @irico1997, thanks for your report. As it turns out, while the bug was fixed, I forgot to deploy it to linguee-api-v2.herokuapp.com. Now it's there and should work as expected.

![Screenshot 2021-06-04 at 07 34 51](https://user-images.githubusercontent.com/75075/120756601-5bc4d000-c507-11eb-8e94-27ad1e91546e.png)
