### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mutasie** [imankulov/linguee-api#11]
Hi Roman,
I started to test version 2 and have tried a few German words to look up translations. There are a few words that I can look up with no problem. However, I encountered issues with the following words. Could you please check? Thank you.

https://linguee-api-pr7.herokuapp.com/api/v2/translations?query=einfach&src=de&dst=en&guess_direction=false
https://linguee-api-pr7.herokuapp.com/api/v2/translations?query=Tisch&src=de&dst=en&guess_direction=false
https://linguee-api-pr7.herokuapp.com/api/v2/translations?query=M%C3%B6glichkei&src=de&dst=en&guess_direction=false

Allen

**Comment by imankulov** [comment]
Thanks for the report, I reproduced and can confirm the issue.

**Comment by imankulov** [comment]
Hey @mutasie, the issue is fixed. You can test the fix on the demo site.

- https://linguee-api-v2.herokuapp.com/api/v2/translations?query=einfach&src=de&dst=en&guess_direction=false
- https://linguee-api-v2.herokuapp.com/api/v2/translations?query=Tisch&src=de&dst=en&guess_direction=false
- https://linguee-api-v2.herokuapp.com/api/v2/translations?query=M%C3%B6glichkei&src=de&dst=en&guess_direction=false
