### ISSUE TITLE
The Linguee server returned 503 for De

### ISSUE THREAD

**Issue by redstoneleo** [imankulov/linguee-api#25]
```
import requests

api_root = "https://linguee-api-v2.herokuapp.com/api/v2"
resp = requests.get(f"{api_root}/translations", params={"query": "Schere", "src": "de", "dst": "en"})
print(resp.json())

for example in resp.json():
    for translation in example["translations"]:
        print(f"{example['text']} -> {translation['text']}")
```

returned

```
{'message': 'The Linguee server returned 503'}
Traceback (most recent call last):
  File "C:\Users\Oscar\Documents\SoftwareProject\DeTranslation\LingueeAPItest.py", line 21, in <module>
    for translation in example["translations"]:
TypeError: string indices must be integers
```

**Comment by Beau-xu** [comment]
Same problem.
Very few German words can be successfully translated into English.

**Comment by imankulov** [comment]
Thanks for the report, folks. Unfortunately, there's not much I can do.

Linguee blocks requests from the same IP address if they happen too often to prevent abuses. Instead of using the demo API endpoint, I recommend installing the project on your Heroku account. It's one click to install and free to use.

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)

**Comment by Beau-xu** [comment]
Hi @imankulov,
Do you know the exact rate limitation of Linguee? I have deployed the project on Heroku but still get blocked when I sent requests every four seconds.

**Comment by Beau-xu** [comment]
Hi @imankulov,
Do you know the exact rate limitation of Linguee? I have deployed the project on Heroku but still get blocked when I sent requests every four seconds.

**Comment by imankulov** [comment]
@Beau-xu, I don't know the exact limit, but I know that it's quite restrictive. Sending requests every four seconds would inevitably result in a ban.
