### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by kgoedert** [imankulov/linguee-api#3]
Hi,

when trying to make requests like this https://linguee-api.herokuapp.com/api?q=plaie&src=fr&dst=en

I am geting a error message like this:

{
    "message": "Internal Server Error",
    "status_code": 500
}

what is wrong with the request above?
Thanks

**Comment by mtford90** [comment]
I'm also experiencing this across most queries.

Sadly I don't know Go otherwise i'd attempt to track this down myself...

**Comment by dmitriyK1** [comment]
Unfortunately I also have this issue on many requests(

**Comment by tommywalkie** [comment]
Looks like issue has been addressed, since https://linguee-api.herokuapp.com/api?q=plaie&src=fr&dst=en looks like it's working now. 👍

**Comment by imankulov** [comment]
Sorry, you had to wait for the response for three years 😅 

I would like to remind you that the endpoint  https://linguee-api.herokuapp.com (and a new one  https://linguee-api-v2.herokuapp.com) is a demo.

To prevent abuses, Linguee blocks requests from the same IP address if they happen too often. Instead of using the demo API endpoint, I recommend installing the project on your own Heroku account. It's one-click to install and free to use.

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)
